ALTER TABLE assets
  ADD COLUMN version INT UNSIGNED NOT NULL DEFAULT 1 AFTER storage_key,
  ADD COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP AFTER created_at;
